name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S tests -B build_tests -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build_tests --config ${{ matrix.build_type }}
    
      - name: Run tests
        run: ctest --test-dir build_tests --output-on-failure
